SELECT 'COFFEES: DID --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: DID --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: DID --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: DID --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: DID --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT CN) > 1
) X;
SELECT 'COFFEES: DID --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DID
	FROM COFFEES
	GROUP BY DID
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: HID --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: HID --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: HID --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: HID --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: HID --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT CN) > 1
) X;
SELECT 'COFFEES: HID --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT HID
	FROM COFFEES
	GROUP BY HID
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: CID --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: CID --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: CID --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: CID --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: CID --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT CN) > 1
) X;
SELECT 'COFFEES: CID --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CID
	FROM COFFEES
	GROUP BY CID
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: DN --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: DN --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: DN --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: DN --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: DN --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT CN) > 1
) X;
SELECT 'COFFEES: DN --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DN
	FROM COFFEES
	GROUP BY DN
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: DS --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: DS --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: DS --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: DS --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: DS --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT CN) > 1
) X;
SELECT 'COFFEES: DS --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT DS
	FROM COFFEES
	GROUP BY DS
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: CN --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: CN --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: CN --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: CN --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: CN --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: CN --> CM' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CN
	FROM COFFEES
	GROUP BY CN
	HAVING COUNT(DISTINCT CM) > 1
) X;
SELECT 'COFFEES: CM --> DID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT DID) > 1
) X;
SELECT 'COFFEES: CM --> HID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT HID) > 1
) X;
SELECT 'COFFEES: CM --> CID' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT CID) > 1
) X;
SELECT 'COFFEES: CM --> DN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT DN) > 1
) X;
SELECT 'COFFEES: CM --> DS' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT DS) > 1
) X;
SELECT 'COFFEES: CM --> CN' AS FD,
	CASE WHEN COUNT(*)=0 THEN 'GILDIR'
	ELSE 'gildir ekki' END AS VALIDITY
FROM (
	SELECT CM
	FROM COFFEES
	GROUP BY CM
	HAVING COUNT(DISTINCT CN) > 1
) X;
